'use strict';
const $=id=>document.getElementById(id);
const KEY='music-hero-rhythm-v1';
const fresh=()=>({done:[false,false,false,false],pattern:[0,0,1,2],best:0});
let state=fresh(), storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved){state.done=state.done.map((_,i)=>saved.done?.[i]===true);if(Array.isArray(saved.pattern)&&saved.pattern.length===4&&saved.pattern.every(n=>[0,1,2].includes(n)))state.pattern=saved.pattern;state.best=Math.max(0,Math.min(100,Number(saved.best)||0));}}catch{storageOK=false;}
let current=0,ctx=null,master=null,timers=[],nodes=[],run=0,busy=false,game=null,tempo=80;
let listened={beat:false,pattern:false,a:false,b:false};
const titles=['Feel the beat','Notes & rests','Choose the tempo','Rhythm Rescue'];
const captions=['Listen & move','Build a pattern','Compare & listen','Your hero challenge'];
const symbols=['♩','♫','𝄽'];
const names=['Quarter note','Two eighth notes','Quarter rest'];
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;}updateStatus();}
function updateStatus(){$('save-status').textContent=storageOK?'Progress stays in this browser.':'Progress lasts for this visit only.';}
function updateChrome(){
 $('missions').innerHTML=titles.map((t,i)=>`<button class="mission ${current===i?'active':''} ${state.done[i]?'done':''}" data-mission="${i}" ${i===3&&!state.done.slice(0,3).every(Boolean)?'disabled':''} ${current===i?'aria-current="step"':''}><span class="number">${state.done[i]?'✓':String(i+1).padStart(2,'0')}</span><span><strong>${t}</strong><small>${i===3&&!state.done.slice(0,3).every(Boolean)?'Finish the 3 lessons':captions[i]}</small></span></button>`).join('');
 const xp=state.done.reduce((s,v,i)=>s+(v?(i===3?40:20):0),0);$('power').value=xp;$('power-label').textContent=`Music Power · ${xp} / 100`;
 document.querySelector('.portrait').classList.toggle('hero',state.done[3]);document.querySelector('.portrait').setAttribute('aria-label',state.done[3]?'Maestro Cat in a blue superhero suit with a red cape':'Maestro Cat, a friendly orange tabby');
 $('cat-state').textContent=state.done[3]?'SUPERHERO MODE':'TEACHER MODE';
 const messages=['Every great rhythm starts with a steady beat. Let’s find yours!','The beat keeps going—even when your hands are silent.','Tempo is the speed of the beat. Listen for the space between sounds.','The concert needs you! Listen first, then echo the rhythm.'];
 $('cat-message').textContent='“'+(state.done[3]?'You brought the concert back to life. Keep listening, creating, and playing!':messages[current])+'”';
 $('badge').classList.toggle('earned',state.done[3]);$('badge').innerHTML=`<span>${state.done[3]?'★':'✧'}</span><div><strong>Rhythm Hero</strong><small>${state.done[3]?'Badge earned. Your rhythm is a superpower!':'Complete the rescue to earn your badge.'}</small></div>`;
 updateStatus();
}
function complete(i){state.done[i]=true;persist();updateChrome();}
function later(fn,seconds){const id=setTimeout(fn,Math.max(0,seconds*1000));timers.push(id);}
function stop(){run++;timers.forEach(clearTimeout);timers=[];nodes.forEach(n=>{try{n.stop();}catch{}});nodes=[];busy=false;game=null;document.querySelectorAll('.beat').forEach(b=>b.classList.remove('lit'));}
async function audio(){try{if(!ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error();ctx=new AC();master=ctx.createGain();master.gain.value=.42;master.connect(ctx.destination);}await ctx.resume();if(ctx.state!=='running')throw Error();return true;}catch{const el=$('feedback')||$('game-status');if(el){el.textContent='Sound could not start. Try the sound button again in a browser with audio enabled.';el.classList.add('wrong');}return false;}}
function sound(at,kind='drum'){
 if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(master);const t=Math.max(at,ctx.currentTime);o.type=kind==='click'?'triangle':'sine';o.frequency.setValueAtTime(kind==='click'?950:180,t);o.frequency.exponentialRampToValueAtTime(kind==='click'?650:65,t+.1);g.gain.setValueAtTime(kind==='click'?.24:.75,t);g.gain.exponentialRampToValueAtTime(.001,t+.14);o.start(t);o.stop(t+.16);nodes.push(o);o.onended=()=>{o.disconnect();g.disconnect();nodes=nodes.filter(n=>n!==o);};
}
function flash(i,delay){later(()=>{document.querySelectorAll('.beat').forEach((b,j)=>b.classList.toggle('lit',j===i%4));},delay);}
function consoleHTML(label='FOLLOW THE PULSE'){return `<div class="console"><span class="console-label">${label}</span><div class="beat-row" aria-hidden="true">${[1,2,3,4].map(n=>`<span class="beat">${n}</span>`).join('')}</div><div class="console-bottom"><span>1 &nbsp; · &nbsp; 2 &nbsp; · &nbsp; 3 &nbsp; · &nbsp; 4</span><span id="console-bpm">80 BPM</span></div></div>`;}
function top(i,intro){return `<div class="lesson-top"><span class="lesson-pill">MISSION 0${i+1} ${i===3?'• +40':'• +20'} POWER</span><span class="duration">${state.done[i]?'✓ Completed':i===3?'Listen → Echo':'About 3 minutes'}</span></div><h2>${titles[i]}${i===0?'.':''}</h2><p class="intro">${intro}</p>`;}
function question(title,options){return `<div class="question"><h3>${title}</h3><div class="answers">${options.map((x,i)=>`<button class="answer" data-answer="${i}">${x}</button>`).join('')}</div><div id="feedback" class="feedback" role="status" aria-live="polite"></div><div id="next"></div></div>`;}
function render(){stop();updateChrome();const w=$('workspace');
 if(current===0){w.innerHTML=top(0,'A beat is music’s steady pulse. Listen to eight beats and gently pat your knees each time a light turns gold.')+consoleHTML()+`<div class="actions"><button class="primary" data-play="beat">▶ Listen & pat along</button><button class="outline" id="stop">Stop sound</button></div><p class="caption">The pulse stays evenly spaced. Count “1, 2, 3, 4” twice.</p>`+question('What makes a beat steady?',['It gets louder every time.','It repeats at even intervals.','It always gets faster.']);}
 if(current===1){w.innerHTML=top(1,'In this lesson, a quarter note gets one beat. Two eighth notes share that beat. A quarter rest gives you one silent beat.')+`<div class="symbol-row">${symbols.map((s,i)=>`<div class="symbol-card"><b aria-hidden="true">${s}</b><span>${names[i]}</span><small>${['1 sound · 1 beat','2 sounds · 1 beat','Silence · 1 beat'][i]}</small></div>`).join('')}</div><div class="question"><h3>Create your four-beat rhythm</h3><p class="caption">Tap each tile to cycle through note, pair, and rest. Try a change, then listen.</p><div id="builder" class="builder"></div><div class="actions"><button class="primary" data-play="pattern">▶ Play my rhythm</button><button class="outline" id="stop">Stop sound</button></div><p class="caption" id="pattern-status">Your pattern is saved on this browser.</p></div>`+question('What happens during a quarter rest?',['The beat disappears.','Play two quick sounds.','Stay silent for one beat; keep the pulse.']);drawBuilder();}
 if(current===2){w.innerHTML=top(2,'Tempo means the speed of the beat. Hear the same four-beat rhythm at two speeds, then compare.')+consoleHTML('LISTEN FOR THE SPEED')+`<div class="actions"><button class="primary" data-play="a">▶ Play A</button><button class="secondary" data-play="b">▶ Play B</button><button class="outline" id="stop">Stop</button></div><p class="caption" id="heard">Listen to both A and B before answering.</p>`+question('Which version has the faster tempo?',['Version A','Version B','Both have the same tempo']);}
 if(current===3){w.innerHTML=top(3,'The concert’s rhythm machine has stopped! Listen to the pattern, then echo it with the tap pad or Space. Aim for 75% to become a Rhythm Hero.')+`<div class="pattern" aria-label="Quarter, quarter, two eighth notes, rest; quarter, quarter, quarter, quarter">${[0,0,1,2,0,0,0,0].map((n,i)=>`<span aria-hidden="true">${symbols[n]}<small>${i%4+1}</small></span>`).join('')}</div><label class="tempo-control">Tempo <input id="tempo" type="range" min="60" max="100" step="5" value="${tempo}" aria-label="Challenge tempo"><strong id="tempo-value">${tempo}</strong> BPM</label>`+consoleHTML('LISTEN → COUNT IN → YOUR TURN')+`<div id="game-status" class="rescue-state" role="status" aria-live="polite">Ready when you are.</div><button id="tap" class="tap-pad">TAP TO PLAY<small>Click, touch, or press Space</small></button><div class="actions"><button class="primary" id="rescue">▶ Start rescue</button><button class="outline" id="stop">Stop / retry</button></div><p class="caption">Listen for 8 beats. Count in for 4. Then play for 8.<br>Best: <span id="best">${state.best}%</span> · Practice score; device timing may vary.</p><div id="result" role="status"></div>`;}
 if(current<3&&state.done[current])showNext();
}
function drawBuilder(){$('builder').innerHTML=state.pattern.map((n,i)=>`<button class="build-cell" data-cell="${i}" aria-label="Beat ${i+1}: ${names[n]}. Activate to change."><b aria-hidden="true">${symbols[n]}</b><small>Beat ${i+1}</small></button>`).join('');}
function showNext(){$('next').innerHTML=`<button class="primary next" data-next="${current+1}">${current===2?'Enter Rhythm Rescue':'Next mission'} →</button>`;}
function selectMission(i){if(!Number.isInteger(i)||i<0||i>3||i===3&&!state.done.slice(0,3).every(Boolean))return false;current=i;render();return true;}
async function play(type){stop();const ticket=run;if(!await audio()||ticket!==run)return;busy=true;const t=ctx.currentTime+.12,bpm=type==='a'?70:type==='b'?120:80,step=60/bpm;const count=type==='beat'?8:4;const pattern=type==='pattern'?state.pattern.slice():[0,0,0,0];const buttons=document.querySelectorAll('[data-play]');buttons.forEach(b=>b.disabled=true);if($('console-bpm'))$('console-bpm').textContent=`${bpm} BPM`;
 for(let i=0;i<count;i++){const n=pattern[i%4];if(n!==2){sound(t+i*step);if(n===1)sound(t+(i+.5)*step);}flash(i,.12+i*step);}
 later(()=>{busy=false;listened[type]=true;buttons.forEach(b=>b.disabled=false);document.querySelectorAll('.beat').forEach(b=>b.classList.remove('lit'));if($('heard'))$('heard').textContent=`A ${listened.a?'✓ heard':'— not yet'} · B ${listened.b?'✓ heard':'— not yet'}`;if($('feedback'))$('feedback').textContent=type==='pattern'?'Listen again after changing a tile, or answer below.':'Now try the question below.';},.12+count*step);
}
function answer(index,el){const correct=[1,2,1][current],f=$('feedback');f.classList.remove('wrong');const ready=current===0?listened.beat:current===1?listened.pattern:listened.a&&listened.b;if(!ready&&!state.done[current]){f.textContent=current===2?'Listen to both versions all the way through first.':'Listen all the way through first, then try the question.';return;}if(index===correct){el.classList.add('correct');f.textContent=['Exactly! Evenly spaced beats make a steady pulse. +20 Music Power.','Yes! Silence belongs in a rhythm, and the pulse keeps going. +20 Music Power.','That’s it! B is 120 BPM; A is 70 BPM. More beats per minute means a faster tempo. +20 Music Power.'][current];if(state.done[current])f.textContent=f.textContent.replace(' +20 Music Power.',' Mission already completed.');complete(current);showNext();}else{f.classList.add('wrong');f.textContent=['Try again. Think about the time between beats.','Try again. A rest is silence with a duration.','Try again. Which version has less time between beats?'][current];}}
const targetOffsets=[0,1,2,2.5,4,5,6,7];
function scoreTaps(targets,taps,tolerance){const used=new Set();let matched=0,early=0,late=0;for(const tap of taps){let best=-1,d=tolerance+1;targets.forEach((t,i)=>{const delta=Math.abs(tap-t);if(!used.has(i)&&delta<d){d=delta;best=i;}});if(best>=0&&d<=tolerance){used.add(best);matched++;if(tap<targets[best]-.07)early++;if(tap>targets[best]+.07)late++;}}const extra=taps.length-matched;return{matched,extra,missed:targets.length-matched,early,late,score:Math.round(100*matched/(targets.length+extra))};}
async function rescue(){stop();const ticket=run;if(!await audio()||ticket!==run)return;busy=true;const step=60/tempo,start=ctx.currentTime+.3,playStart=start+12*step;game={start:playStart,end:playStart+8*step,taps:[],targets:targetOffsets.map(n=>playStart+n*step),tolerance:Math.min(.22,step*.28)};$('rescue').disabled=true;$('tempo').disabled=true;$('result').innerHTML='';$('game-status').textContent='Listen to Maestro: 8 beats.';$('console-bpm').textContent=`${tempo} BPM`;targetOffsets.forEach(n=>sound(start+n*step));
 for(let i=0;i<20;i++){const t=start+i*step;flash(i,t-ctx.currentTime);if(i>=8)sound(t,'click');if(i===8)later(()=>{$('game-status').textContent='Get ready… 1, 2, 3, 4.';},t-ctx.currentTime);if(i===12)later(()=>{$('game-status').textContent='Your turn! Echo the pattern.';$('tap').focus({preventScroll:true});},t-ctx.currentTime);}
 later(finishRescue,game.end-ctx.currentTime+.23);
}
function tap(){if(!ctx)return;sound(ctx.currentTime);const pad=$('tap');pad.classList.add('pressed');later(()=>pad?.classList.remove('pressed'),.1);if(game){const time=ctx.currentTime;if(time>=game.start-game.tolerance&&time<=game.end)game.taps.push(time);}}
function finishRescue(){if(!game)return;const result=scoreTaps(game.targets,game.taps,game.tolerance);game=null;busy=false;$('rescue').disabled=false;$('tempo').disabled=false;document.querySelectorAll('.beat').forEach(b=>b.classList.remove('lit'));state.best=Math.max(state.best,result.score);persist();$('best').textContent=`${state.best}%`;const passed=result.score>=75;if(passed){complete(3);document.querySelector('.portrait').classList.add('celebrate');}const advice=result.extra?'Keep the rest silent, and avoid extra taps.':result.missed?'Watch the beat lights and try a slower tempo.':'You kept the rhythm moving!';$('game-status').textContent=passed?'SUPERHERO MODE ACTIVATED!':'Good practice. Ready for another try?';$('result').innerHTML=`<div class="result"><h3>${passed?'★ Rhythm Hero!':`${result.score}% — keep practicing`}</h3><p>${result.score}% · ${result.matched}/8 sounds matched · ${result.extra} extra taps.</p><p>${passed?'You saved the concert and earned your badge!':advice}</p></div>`;}
$('workspace').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.play)play(b.dataset.play);else if(b.dataset.answer!==undefined)answer(Number(b.dataset.answer),b);else if(b.dataset.next) {selectMission(Number(b.dataset.next));$('workspace').focus();}else if(b.dataset.cell!==undefined){if(busy){stop();render();}const i=Number(b.dataset.cell);state.pattern[i]=(state.pattern[i]+1)%3;persist();drawBuilder();}else if(b.id==='stop'){stop();render();}else if(b.id==='rescue')rescue();else if(b.id==='tap')tap();});
$('missions').addEventListener('click',e=>{const b=e.target.closest('[data-mission]');if(b&&!b.disabled)selectMission(Number(b.dataset.mission));});
$('workspace').addEventListener('input',e=>{if(e.target.id==='tempo'){tempo=Number(e.target.value);$('tempo-value').textContent=tempo;}});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&current===3&&!e.repeat&&!document.querySelector('dialog[open]')&&!['INPUT','TEXTAREA'].includes(e.target.tagName)&&(!e.target.closest('button')||e.target.id==='tap')){e.preventDefault();tap();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&busy){stop();render();if($('game-status'))$('game-status').textContent='Paused while you were away. Start again when ready.';}});
$('teacher-open').onclick=()=>{stop();render();$('teacher').showModal();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('reset').onclick=()=>$('reset-dialog').showModal();
$('confirm-reset').onclick=()=>{stop();state=fresh();current=0;listened={beat:false,pattern:false,a:false,b:false};persist();$('reset-dialog').close();render();};
try{$('reflection').value=localStorage.getItem(KEY+'-reflection')||'';}catch{}
$('reflection').oninput=()=>{try{localStorage.setItem(KEY+'-reflection',$('reflection').value);}catch{$('reflection').nextElementSibling.textContent='Notes could not be saved on this browser.';}};
$('standards').innerHTML=[['P.8.5.2','Pattern practice: keep a consistent tempo.'],['Lr.5.5.1','Tempo vocabulary applied to listening examples.'],['Cn.1.5.1','Discuss how personal interests shape musical choices.'],['Cr.11.5.1','Extension: add words, tempo, and dynamics to the created rhythm, then perform it.']].map(([code,desc])=>`<div class="standard"><strong>${code}</strong> · ${desc}</div>`).join('');
render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_rhythm_progress',description:'Read completed missions, music power, and best practice score for this browser.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return{mission:current+1,completed:state.done.map((v,i)=>v?i+1:null).filter(Boolean),power:Number($('power').value),best:state.best};}});register({name:'open_rhythm_mission',description:'Navigate to an unlocked mission without completing it or starting audio.',inputSchema:{type:'object',properties:{mission:{type:'integer',minimum:1,maximum:4}},required:['mission'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isInteger(input.mission)||!selectMission(input.mission-1))throw Error('Mission is invalid or locked. Complete the three lessons to unlock mission 4.');return{opened:current+1,title:titles[current]};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
