'use strict';
const CAT=window.CAT_DATA||Object.fromEntries(['sit','side','jump','stretch','eat','fly','hero','heroside','heroback','victory','alert'].map(p=>[p,'assets/cats/'+p+'.webp']));
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const catImg=(pose,cls='',alt='')=>`<img src="${CAT[pose]}" class="${cls}${FLIP[pose]?' flip':''}" alt="${esc(alt)}">`;
const FLIP={side:1,jump:1,stretch:1,eat:1};
const FACE=`background-image:url(${CAT.sit});background-size:250%;background-position:50% 14%`;
document.querySelectorAll('.face').forEach(f=>f.setAttribute('style',FACE));
$('hero-img').src=CAT.jump;

const KEY='music-teaching-studio-v2';
const FIELDS=[
 ['objective','Learning objective','What will learners do, under what conditions, and what evidence will show success?'],
 ['explanation','Explain it to children','Use accurate, age-appropriate words. Include an example and a contrasting non-example.'],
 ['prepare','1. Experience before the label','Describe what children will hear, sing, move, or play before you name the concept.'],
 ['present','2. Name and connect','How will you connect the sound they experienced to the definition or notation?'],
 ['practice','3. Apply in a new musical task','What will children perform, create, listen for, or change? Explain what stays the same.'],
 ['assessment','Evidence and next teaching move','What will you observe in an individual response? What will you do if the concept is not yet secure?'],
 ['access','Participation and access','Provide a meaningful alternate way to demonstrate the same musical understanding.'],
 ['rationale','Why this sequence?','Explain the musical and pedagogical reasons for your decisions, including a relevant standards connection.']
];
const LENSES=[['accuracy','Concept clarity','explanation'],['experience','Musical experience','prepare'],['evidence','Evidence of learning','assessment'],['access','Participation and access','access'],['sequence','Sequence and transfer','rationale']];
const GRADES=['K','1','2','3','4','5','6'];
let db={drafts:{}},storageOK=true,page='library',selected='concept-5',filters={grade:'all',domain:'all',query:''},compareId=null,restoreId=null,audioContext=null,audioNodes=[],audioTimer=null;
try{const loaded=JSON.parse(localStorage.getItem(KEY));if(loaded&&typeof loaded.drafts==='object'&&loaded.drafts&&!Array.isArray(loaded.drafts))db=loaded;}catch{storageOK=false;}
const concept=()=>CONCEPTS.find(c=>c.id===selected)||CONCEPTS[5];
function draft(){const c=concept();if(!db.drafts[c.id])db.drafts[c.id]={fields:Object.fromEntries(FIELDS.map(f=>[f[0],''])),grade:c.grade,scenario:0,decision:null,dialogue:[],reviews:{},versions:[],lens:'accuracy',turns:{}};const d=db.drafts[c.id];d.fields={...Object.fromEntries(FIELDS.map(f=>[f[0],''])),...d.fields};d.dialogue=Array.isArray(d.dialogue)?d.dialogue:[];d.versions=Array.isArray(d.versions)?d.versions:[];d.reviews=d.reviews||{};d.turns=d.turns||{};return d;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));}catch{storageOK=false;}$('save-status').textContent=storageOK?'Drafts and reflections stay in this browser.':'Browser saving is unavailable. Export your work before leaving.';const s=$('draft-status');if(s)s.textContent=storageOK?'Saved in this browser.':'Not saved. Export your work before leaving.';updateCount();}
function toast(s){$('toast-text').textContent=s;$('toast').style.display='flex';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4000);}
function updateCount(){$('revision-count').textContent=Object.values(db.drafts).reduce((n,d)=>n+(Array.isArray(d.versions)?d.versions.length:0),0);}

/* Maestro Cat companion */
const TIPS=['Children should hear it before they name it. What will they hear first?','Keep one feature changing and everything else steady. That is how a contrast becomes audible.','"Does everyone understand?" gives you a chorus of yeses. Ask for something you can see or hear instead.','A group performance can hide uncertainty. Listen to one or two individuals before you move on.','Revising with a reason is growth. Revising without one is just rearranging.','An alternate response route should still show the same musical thinking.'];
const PAGE_CAT={studio:['side','What would children actually do to show that they understand? Start there.'],revisions:['eat','Old drafts are good snacks for thinking. Compare one with your current plan.']};
let tipIndex=0,dockTimer=null;
function say(text,pose,ms=7000){const img=$('dock-img');if(pose){img.src=CAT[pose];img.classList.toggle('flip',!!FLIP[pose]);img.classList.remove('pop');void img.offsetWidth;img.classList.add('pop');}$('dock-text').textContent=text;$('dock-bubble').classList.remove('hide');clearTimeout(dockTimer);if(ms&&window.innerWidth<700)ms=Math.min(ms,4500);if(ms)dockTimer=setTimeout(()=>$('dock-bubble').classList.add('hide'),ms);}
$('dock-cat').onclick=()=>{say(TIPS[tipIndex++%TIPS.length],null,9000);};
$('dock-close').onclick=()=>$('dock-bubble').classList.add('hide');

/* Navigation */
function select(id){if(!CONCEPTS.some(c=>c.id===id))throw Error('Unknown concept');stopAudio();selected=id;compareId=null;renderList();render();}
function navigate(p){if(!['library','studio','revisions','rhythm'].includes(p))throw Error('Unknown workspace');stopAudio();rStop();page=p;document.querySelectorAll('nav.tabs [data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===p);b.toggleAttribute('aria-current',b.dataset.page===p);});render();try{history.replaceState(null,'',p==='library'?location.pathname+location.search:'#'+p);}catch{}if(PAGE_CAT[p])say(PAGE_CAT[p][1],PAGE_CAT[p][0]);if(p!=='library')window.scrollTo({top:0});}
function renderStaff(){const st=$('staff');st.querySelectorAll('.note').forEach(n=>n.remove());GRADES.forEach((g,i)=>{const b=document.createElement('button');b.className='note';b.dataset.grade=g;b.style.left=(14+i*12.5)+'%';b.style.bottom=(12+i*12)+'px';b.setAttribute('aria-pressed',filters.grade===g);b.setAttribute('aria-label',g==='K'?'Kindergarten concepts':`Grade ${g} concepts`);const n=CONCEPTS.filter(c=>c.grade===g).length;b.innerHTML=`<span class="stem"></span><span class="head"><b>${g}</b></span><span class="cap">${n} concepts${g==='6'?', proposed':''}</span>`;st.appendChild(b);});}
function setGrade(g){filters.grade=g;$('grade').value=g;renderStaff();renderList();const first=CONCEPTS.find(c=>g==='all'||c.grade===g);if(first&&g!=='all'&&concept().grade!==g)select(first.id);$('staff-label').textContent=g==='all'?'Pick a grade on the staff. The notes climb from kindergarten to grade 6.':`Showing ${g==='K'?'kindergarten':'grade '+g}. Tap the same note again to show every grade.`;}
function renderList(){const found=CONCEPTS.filter(c=>(filters.grade==='all'||c.grade===filters.grade)&&(filters.domain==='all'||c.domain===filters.domain)&&`${c.name} ${c.child} ${c.teacher}`.toLowerCase().includes(filters.query.toLowerCase()));$('concept-count').textContent=found.length+' shown';let last='';$('concept-list').innerHTML=found.length?found.map(c=>{const group=c.grade!==last?`<div class="group-label">${c.grade==='K'?'Kindergarten':'Grade '+esc(c.grade)}${c.proposed?', proposed':''}</div>`:'';last=c.grade;return group+`<button class="concept-button ${c.id===selected?'active':''}" data-concept="${c.id}" ${c.id===selected?'aria-current="true"':''}>${esc(c.name)}<small>${esc(c.domain)}, grade ${esc(c.grade)}</small></button>`;}).join(''):'<p class="small">No concepts match. Try another grade or search term.</p>';}

/* Library */
function experiences(c){return [
 {title:'Listen, notice, and respond',body:c.experience,field:'prepare'},
 {title:'Perform through another pathway',body:({Melody:`Echo a short example of ${c.name.toLowerCase()} using a comfortable voice or an instrument. Trace its pitch relationships with movement, then explain which relationship the movement represents.`,Rhythm:`Perform the pattern with voice, body percussion, or a classroom instrument. Have a partner keep a pulse or show durations. Switch roles and describe how ${c.name.toLowerCase()} shaped the sound.`,Form:`Give each section a gesture or shape. Perform the sections in order, then use the map to anticipate the next section. Ask which sound justified each boundary.`,Texture:`Learn each part separately. Combine the layers or alternate roles as appropriate, and ask learners to describe what each performer contributed.`,Expression:`Perform the same short phrase twice with one expressive choice changed. Keep unrelated features stable so learners can identify the effect of ${c.name.toLowerCase()}.`,Other:`Model ${c.name.toLowerCase()} through the concrete example above. Let learners demonstrate it with an instrument, voice, movement, or a score-card route, as appropriate.`})[c.domain],field:'practice'},
 {title:'Create, explain, and revise',body:`Invite a pair to make a brief musical example that demonstrates ${c.name.toLowerCase()}. Another pair identifies the evidence. Revise one feature if the concept is unclear; explain what changed and why.`,field:'practice'}
];}
function standards(grade){const band=grade==='K'||Number(grade)<=2?'K to 2':Number(grade)<=5?'3 to 5':'6 to 8';const rows=band==='K to 2'?[['P.8.2.2','Echo/read patterns and maintain a steady beat on an instrument.'],['Lr.5.2.1','Demonstrate expressive qualities using musical vocabulary.'],['Cr.11.2.1','Represent simple rhythms with notation.']]:band==='3 to 5'?[['P.8.5.2','Perform patterns at a consistent tempo.'],['Lr.5.5.1','Apply expressive music vocabulary to examples.'],['Cr.11.5.1','Plan, notate, and perform rhythmic speech with text and expressive indicators.']]:[['P.8.8.1','Perform modeled/notated pitches and rhythms with appropriate technique.'],['Lr.5.8.2','Describe how musical elements appear in an example.'],['Cr.11.8.2','Compose within guidelines and explain use of musical elements.']];return `<p><strong>Grade band ${band}.</strong> Possible connections to verify against your task.</p>${rows.map(([code,t])=>`<p><strong>${code}</strong><br>${t}</p>`).join('')}<p>These are selected reference points, not automatic alignment. Consult the full standards for melody, form, texture, and other goals.</p>`;}
function demoType(c){if(['Steady beat','Rhythm','Beat and rhythm together'].includes(c.name))return'beat';if(c.name==='High and low pitch')return'pitch';if(['Loud and quiet','Forte and piano','Crescendo and decrescendo'].includes(c.name))return'dynamics';if(c.name.startsWith('Compound meter'))return'meter';return null;}
function library(){const c=concept(),ex=experiences(c),demo=demoType(c);$('content').innerHTML=`<div class="library"><article class="surface" style="overflow:hidden"><div class="concept-top"><span class="crumb">${esc(c.domain)} concept</span><h2>${esc(c.name)}</h2><span class="pill">${c.grade==='K'?'Kindergarten':'Grade '+c.grade}</span><span class="pill">${c.domain}</span>${c.proposed?'<span class="pill proposed">Proposed extension</span>':'<span class="pill">From your outline</span>'}</div><div class="definition"><h3>A definition for children</h3><p class="child-definition">${esc(c.child)}</p><p class="teacher-note"><b>Teacher precision.</b> ${esc(c.teacher)}</p></div><div class="section-body"><div class="misconception"><div><b>Anticipate this misconception</b>${esc(c.misconception)}</div></div><h3>One concept, several musical experiences</h3><p class="small" style="margin-bottom:10px">Each experience can become a planning seed in the Teaching studio.</p>${ex.map((x,i)=>`<div class="experience"><span>${i+1}</span><div><h4>${x.title}</h4><p>${esc(x.body)}</p><button class="linkish" data-idea="${i}">Use as a planning seed</button></div></div>`).join('')}${demo?`<div class="demo"><div><h4>Try it before you teach it</h4><p>${{beat:'Compare a steady pulse with a rhythm over the same pulse.',pitch:'Compare two pitches at the same volume. Then hear a quiet high note.',dynamics:'Hear the same pitch at two volumes, then a gradual crescendo.',meter:'Hear two main beats, first divided in two and then divided in three.'}[demo]}</p><button data-audio="${demo}">Play comparison</button><button class="stop" data-stop-audio>Stop</button><span id="audio-state" class="state" role="status">Original synthesized examples. No recording required.</span></div>${catImg('sit','demo-cat','Maestro Cat listening')}</div>`:''}</div></article>
<aside class="aside"><div class="mentor">${catImg('sit','mentor-cat','Maestro Cat sitting and smiling')}<h3>Maestro Cat</h3><div class="role">Your teaching partner</div><blockquote>What would children actually do to show that they understand?</blockquote><p>Bring this concept into a classroom scenario. Draft your approach, examine the evidence, and revise.</p><button class="btn-gold" data-nav="studio">Design a learning experience</button></div><div class="surface mini"><h3>The learning cycle</h3><ol class="cycle">${['Experience the sound','Connect the concept','Apply and create','Observe and adapt'].map(t=>`<li>${t}</li>`).join('')}</ol><p>This is a planning scaffold. Readiness may develop across several lessons.</p></div><div class="surface mini"><h3>Indiana standards lens</h3>${standards(c.grade)}<button class="linkish" data-sources>Open source notes</button></div></aside></div>`;}

/* Studio */
function scenarioText(c,d){const g=d.grade;return [
 {title:'They can follow you. Can they do it independently?',body:`You are teaching Grade ${g}. Learners can copy your demonstration of ${c.name.toLowerCase()}, but it is unclear whether they understand it without your model. You have 12 minutes, your voice, and a few classroom instruments. Plan an experience that reveals each learner's thinking.`,prompt:'What will you do first?',choices:['Repeat the definition, then ask "Does everyone understand?"','Offer two contrasting musical examples and ask learners to show or explain the difference.','Show the notation and ask learners to copy it neatly.'],feedback:['A definition can help later, but agreement alone gives little evidence. Begin with an observable musical response, then connect it to the words.','A contrast can make the concept audible and reveal learners\' thinking. Keep unrelated features stable, and decide what response would count as evidence.','Notation can support understanding after sound has meaning. First check that learners can hear or perform the relationship the symbol represents.']},
 {title:'Keep the musical goal. Change the access route.',body:`In Grade ${g}, students are exploring ${c.name.toLowerCase()}. Some are hesitant to sing alone; another learner needs an alternative to whole-body movement. You have 15 minutes and mixed experience levels. Create ways to participate that preserve the same musical goal.`,prompt:'Which adaptation best preserves evidence of understanding?',choices:['Excuse those learners from the musical task and give them coloring.','Offer partner singing, an instrument, or a gesture/selection response that demonstrates the target relationship.','Require everyone to use the same movement or vocal response for fairness.'],feedback:['An unrelated task removes the musical learning opportunity. Identify the concept evidence first, then design another route to provide it.','A choice can preserve access when it still reveals the same understanding. Explain exactly what the alternative response demonstrates.','Identical participation does not guarantee equal access. Keep the learning target consistent while adapting the response mode.']},
 {title:'The performance worked. What should happen next?',body:`A Grade ${g} group performed a rehearsed example of ${c.name.toLowerCase()} successfully. Now they must transfer the idea to a new musical example. You have 10 minutes. Decide what stays the same, what changes, and how you will respond if transfer breaks down.`,prompt:'Which next task tests transfer most directly?',choices:['Repeat the exact example until it is faster.','Give an unfamiliar example of the same concept and ask learners to perform, identify, or create it with a reason.','Tell learners that a polished group performance proves everyone understands.'],feedback:['Fluency is useful, but repetition alone does not establish transfer. Change a relevant surface feature while preserving the concept.','This can show transfer. Avoid changing too many features at once, and plan how to hear from individuals as well as the group.','A group can conceal uncertainty. Collect a brief individual or partner response before deciding everyone is ready to move on.']}
][d.scenario||0];}
const SCENARIO_CAT=['alert','heroside','victory'];
function studio(){const c=concept(),d=draft(),sc=scenarioText(c,d);$('content').innerHTML=`<div class="page-head"><div><span class="crumb">Teaching studio, ${esc(c.domain)}</span><h2>${esc(c.name)}</h2><p>Build a teachable sequence. Revise with a reason.</p></div><button class="secondary" data-nav="library">Review the concept</button></div>
<section class="scenario"><span class="tag">Classroom scenario</span><h3>${sc.title}</h3><p>${esc(sc.body)}</p><label for="scenario-select">Practice context</label><select id="scenario-select">${['Independent understanding','Participation and access','Transfer to a new example'].map((t,i)=>`<option value="${i}" ${d.scenario===i?'selected':''}>${t}</option>`).join('')}</select><details ${d.decision!==null?'open':''}><summary>${sc.prompt}</summary><div class="decisions">${sc.choices.map((v,i)=>`<button data-decision="${i}" aria-pressed="${d.decision===i}">${String.fromCharCode(65+i)}. ${esc(v)}</button>`).join('')}</div><p class="decision-feedback" role="status">${d.decision!==null?esc(sc.feedback[d.decision]):''}</p></details>${catImg(SCENARIO_CAT[d.scenario||0],'scenario-cat','')}</section>
<div class="studio-cols"><div><section class="surface draft"><h3>Your lesson draft</h3><p>Use the prompts to make your thinking visible. A short, specific plan is more useful than a long list of activities.</p><label for="target-grade">Teaching grade <small>Adjust to your learners' readiness; source placement is ${c.grade==='K'?'kindergarten':'grade '+c.grade}.</small></label><select id="target-grade">${GRADES.map(g=>`<option ${d.grade===g?'selected':''}>${g}</option>`).join('')}</select>${FIELDS.map(([id,label,hint])=>`<label for="field-${id}">${label}<small>${hint}</small></label><textarea id="field-${id}" data-field="${id}" maxlength="6000" rows="3" placeholder="Write your teaching decisions here">${esc(d.fields[id])}</textarea>`).join('')}<div class="actions"><button class="primary" id="review-draft">Review my draft</button><button class="secondary" id="snapshot">Save revision</button><button class="secondary" id="export">Export lesson</button></div><p id="draft-status" class="draft-status">Saved in this browser.</p></section>
<section class="surface review"><h3>Self-review with evidence</h3><p>Choose a status and point to evidence from your plan. These are your judgments, not automated scores.</p>${LENSES.map(([id,label])=>`<div class="rubric-row"><label for="review-${id}">${label}<small>${rubricHint(id)}</small></label><select id="review-${id}" data-review="${id}">${['Not reviewed','Needs revision','Evidence identified'].map(v=>`<option ${d.reviews[id]?.status===v?'selected':''}>${v}</option>`).join('')}</select><input aria-label="Evidence for ${label}" data-evidence="${id}" value="${esc(d.reviews[id]?.evidence||'')}" placeholder="Which phrase, task, or learner response is your evidence?" maxlength="1200"></div>`).join('')}</section></div>
<aside class="surface coach"><div class="coach-head"><span class="face lg" style="${FACE}" aria-hidden="true"></span><div><h3>Coaching with Maestro</h3><span>Authored prompts, not generative AI</span></div></div><p>Choose a focus, write a response, then use the follow-up to revise your draft.</p><label for="lens">What do you want to develop?</label><select id="lens">${LENSES.map(([id,label])=>`<option value="${id}" ${d.lens===id?'selected':''}>${label}</option>`).join('')}</select><button class="secondary full" id="coach-prompt">Ask me a coaching question</button><div id="conversation" class="conversation" aria-live="polite"></div><label for="coach-response">Your response or revision rationale</label><textarea id="coach-response" rows="3" maxlength="2000" placeholder="I would... because... The evidence I would look for is...">${esc(d.reply||'')}</textarea><button class="primary full" id="coach-send" style="margin-top:10px">Reflect and continue</button><p class="lens-note small">Responses are saved for reflection. The next question follows your selected focus; the coach does not evaluate the meaning of your text.</p><details><summary>Check the concept</summary><p>${esc(c.child)}</p><p><strong>Watch for:</strong> ${esc(c.misconception)}</p></details><details><summary>Standards to consider</summary>${standards(d.grade)}</details></aside></div>`;renderDialogue();}
function rubricHint(id){return {accuracy:'Correct definition, useful contrast, no central misconception.',experience:'Children actively hear, move, sing, play, or create the target idea.',evidence:'An observable response linked to the goal and a next teaching move.',access:'Another route to demonstrate the same musical understanding.',sequence:'A reason for the order, plus an application to a new example.'}[id];}
function renderDialogue(){const d=draft();if(!$('conversation'))return;const face=`<span class="face" style="${FACE}" aria-hidden="true"></span>`;$('conversation').innerHTML=d.dialogue.length?d.dialogue.map(m=>m.role==='learner'?`<div class="msg me"><div class="body"><b>Your reflection</b><p>${esc(m.text)}</p></div></div>`:`<div class="msg">${face}<div class="body"><b>Maestro Cat</b><p>${esc(m.text)}</p></div></div>`).join(''):`<div class="msg">${face}<div class="body"><b>Maestro Cat</b><p>Write a first draft, even an incomplete one. Pick a focus, and I will ask a concept-specific question to help you examine it.</p></div></div>`;$('conversation').scrollTop=$('conversation').scrollHeight;}
function coachingQuestion(lens,turn){const c=concept(),d=draft();const prompts={accuracy:[`Your child-facing anchor is: "${c.child}"\nCompare that with your explanation. Which words preserve the musical meaning, and which might need an example?`,`Test this misconception: "${c.misconception}"\nDesign an example and a non-example. What feature will you keep constant so children can hear the distinction?`,`How could a child demonstrate ${c.name.toLowerCase()} without repeating your definition? Add that demonstration to your plan.`],experience:[`Start from this musical seed: ${c.experience}\nWhat will every child actively do before you introduce the term?`,`Move the same concept into a second musical pathway: listening, singing, movement, playing, or creating. What stays musically constant across both experiences?`,`Now make the learner a decision-maker. What could children choose, create, or change that would make their understanding audible?`],evidence:[`What individual response would convince you that a learner understands ${c.name.toLowerCase()}? Replace "students understand" with something you can hear or see.`,`Imagine a learner copies you successfully but cannot explain or transfer the idea. What brief contrast or new example would help you distinguish imitation from understanding?`,`Write an if/then teaching move: "If I observe __, I will __." How will you check whether your adaptation helped?`],access:[`Keep the goal ${c.name.toLowerCase()} in view. If singing alone, reading notation, hearing the example, or moving around is a barrier, which alternative could reveal the same relationship?`,`Compare your main task and alternative response. Do they require the same musical reasoning? Describe the evidence you would collect from each.`,`Plan a choice of participation routes and an appropriate challenge for a learner who is already ready. Explain how you will avoid labeling children by ability.`],sequence:[`Explain why your first activity comes before naming ${c.name.toLowerCase()}. What readiness evidence would tell you it is time to introduce the label?`,`Choose one new example for transfer. Which surface feature will change, and which musical relationship must remain stable?`,`Connect your objective, task, and assessment. Identify one mismatch and revise it; cite the relevant Indiana standard only if the task actually addresses it.`]};let text=prompts[lens][turn%3];const field=LENSES.find(x=>x[0]===lens)?.[2];if(turn===0&&d.fields[field]?.trim())text=`From your draft (${FIELDS.find(x=>x[0]===field)[1]}):\n"${d.fields[field].slice(0,500)}"\n\n`+text;return text;}
function addPrompt(){const d=draft();const t=d.turns[d.lens]||0;d.dialogue.push({role:'coach',text:coachingQuestion(d.lens,t),at:Date.now()});d.turns[d.lens]=t+1;save();renderDialogue();}
function reviewDraft(){const d=draft();const missing=FIELDS.filter(f=>!d.fields[f[0]].trim()).map(f=>f[1]);let text=missing.length?`Draft structure check: these sections are still empty: ${missing.join('; ')}. Choose one to develop first.`:'Every draft section contains text. This is a completeness check, not a judgment of instructional quality.';text+=`\n\nConcept accuracy checkpoint: ${concept().misconception}\nCompare your explanation and example against this distinction. Then examine whether your assessment requires the same musical thinking as your objective.`;const unsupported=LENSES.filter(([id])=>d.reviews[id]?.status==='Evidence identified'&&!d.reviews[id]?.evidence?.trim());if(unsupported.length)text+='\n\nAdd evidence for your self-review claims: '+unsupported.map(x=>x[1]).join(', ')+'.';d.dialogue.push({role:'coach',text,at:Date.now()});save();renderDialogue();say(missing.length?`${missing.length} section${missing.length>1?'s are':' is'} still empty. My notes are in the coaching panel.`:'Every section has text. Now check the misconception note in the coaching panel.','alert');}
function snapshot(reason='Saved revision'){const d=draft();if(!FIELDS.some(([id])=>d.fields[id].trim())){toast('Write part of your draft before saving a revision.');return false;}d.versions.push({id:Date.now()+'-'+Math.random().toString(36).slice(2,7),at:new Date().toISOString(),reason,fields:{...d.fields},grade:d.grade,scenario:d.scenario,reviews:JSON.parse(JSON.stringify(d.reviews))});save();return true;}

/* Revisions */
function revisions(){const c=concept(),d=draft();$('content').innerHTML=`<div class="page-head"><div><span class="crumb">Revision history, ${esc(c.name)}</span><h2>Make your growth visible.</h2><p>Snapshots preserve your teaching decisions. Compare a saved version with your working draft.</p></div><button class="primary" data-nav="studio">Continue drafting</button></div>${d.versions.length?d.versions.slice().reverse().map((v,i)=>`<article class="surface rev-card"><h3>Revision ${d.versions.length-i}, grade ${esc(v.grade)}</h3><div class="rev-meta">${esc(new Date(v.at).toLocaleString())}. ${esc(v.reason)}</div><p class="small">${esc((v.fields.objective||v.fields.explanation||'Lesson in progress').slice(0,180))}</p><div class="actions"><button class="secondary" data-compare="${v.id}">Compare with current</button><button class="secondary" data-restore="${v.id}">Restore this version</button></div></article>`).join(''):`<section class="surface empty">${catImg('stretch','','Maestro Cat stretching')}<div><h3>No saved revisions for this concept yet.</h3><p>Your working draft saves automatically. Use "Save revision" in the Teaching studio to keep a comparison point, then come back here to see what changed.</p><button class="primary" data-nav="studio">Open the Teaching studio</button></div></section>`}<section id="comparison"></section>`;if(compareId)renderComparison();}
function renderComparison(){const d=draft(),v=d.versions.find(v=>v.id===compareId);if(!v)return;const changed=FIELDS.filter(([id])=>v.fields[id]!==d.fields[id]).length;$('comparison').innerHTML=`<article class="surface rev-card"><h3>Saved revision compared with working draft</h3><p class="small">${changed} of ${FIELDS.length} draft sections changed. Changed text is not automatically better; explain why the revision helps learning.</p>${FIELDS.map(([id,label])=>`<div class="compare-field"><h4>${label}${v.fields[id]!==d.fields[id]?'<span class="changed">Changed</span>':'<span class="same">Unchanged</span>'}</h4><div class="compare-grid"><div><h5>Saved</h5><p>${esc(v.fields[id]||'Not yet written')}</p></div><div><h5>Current</h5><p>${esc(d.fields[id]||'Not yet written')}</p></div></div></div>`).join('')}</article>`;}
function exportLesson(){const c=concept(),d=draft();const text=`# Teaching draft: ${c.name}\n\nTeaching grade: ${d.grade}\nSource placement: ${c.grade}${c.proposed?' (proposed extension)':''}\n\n## Concept anchor\n${c.child}\n\nTeacher precision: ${c.teacher}\n\n## Scenario\n${scenarioText(c,d).body}\n\n`+FIELDS.map(([id,label])=>`## ${label}\n${d.fields[id]||'[Not yet written]'}\n`).join('\n')+'\n## Self-review\n'+LENSES.map(([id,label])=>`${label}: ${d.reviews[id]?.status||'Not reviewed'}\nEvidence: ${d.reviews[id]?.evidence||'[Not provided]'}`).join('\n\n')+'\n\n## Guided reflection dialogue\n'+d.dialogue.map(m=>`${m.role==='learner'?'Learner':'Guided coach'}: ${m.text}`).join('\n\n')+'\n\nCoaching uses authored prompts and completeness checks, not generative AI or automated quality grading.\nStandards source: https://www.in.gov/doe/files/IAS-Grades-K-12-Music.pdf\n';
 try{const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=c.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-teaching-draft.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{}
 if(navigator.clipboard?.writeText){navigator.clipboard.writeText(text).then(()=>toast('Lesson copied to your clipboard as Markdown. Paste it into any document.')).catch(()=>toast('Export started. If no file appears, select and copy your draft fields.'));}else toast('Export started. If no file appears, select and copy your draft fields.');}

function render(){document.body.dataset.page=page;$('hero').hidden=page!=='library';updateCount();if(page==='library')library();if(page==='studio')studio();if(page==='revisions')revisions();if(page==='rhythm')rRender();$('save-status').textContent=storageOK?'Drafts and reflections stay in this browser.':'Browser saving is unavailable. Export your work before leaving.';}

/* Concept audio demos */
function stopAudio(){audioNodes.forEach(n=>{try{n.stop();}catch{}});audioNodes=[];clearTimeout(audioTimer);const dc=document.querySelector('.demo-cat');if(dc){dc.classList.remove('bounce');dc.src=CAT.sit;dc.classList.remove('flip');}if($('audio-state'))$('audio-state').textContent='Stopped.';}
async function ensureAudio(){if(!audioContext){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error();audioContext=new AC();}await audioContext.resume();if(audioContext.state!=='running')throw Error();}
async function playDemo(type){stopAudio();try{await ensureAudio();const now=audioContext.currentTime+.15;const tone=(offset,pitch=0,amp=.13,dur=.14)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=pitch||440;o.connect(g);g.connect(audioContext.destination);g.gain.setValueAtTime(.001,now+offset);g.gain.exponentialRampToValueAtTime(amp,now+offset+.015);g.gain.exponentialRampToValueAtTime(.001,now+offset+dur);o.start(now+offset);o.stop(now+offset+dur+.02);audioNodes.push(o);o.onended=()=>{o.disconnect();g.disconnect();};};let length=8;
 if(type==='beat'){for(let i=0;i<4;i++)tone(i*.6,220,.15);for(let i=0;i<4;i++)tone(3+i*.6,220,.07);[0,.5,1.5,2,3,3.5].forEach(i=>tone(3+i*.6,660,.15));length=6;}
 if(type==='pitch'){tone(0,262,.13,.6);tone(1,523,.13,.6);tone(2.4,523,.04,.6);length=3.4;}
 if(type==='dynamics'){tone(0,440,.04,.6);tone(1,440,.2,.6);for(let i=0;i<5;i++)tone(2.5+i*.5,440,.035+i*.035,.3);length=5.3;}
 if(type==='meter'){[0,.5,1,1.5].forEach((v,i)=>tone(v,i%2===0?330:660,i%2===0?.16:.07));[0,1/3,2/3,1,4/3,5/3].forEach((v,i)=>tone(3+v,i%3===0?330:660,i%3===0?.16:.07));length=5.2;}
 const dc=document.querySelector('.demo-cat');if(dc){dc.src=CAT.jump;dc.classList.add('flip','bounce');}
 if($('audio-state'))$('audio-state').textContent='Playing. Listen for the feature that changes.';audioTimer=setTimeout(()=>{if(dc){dc.classList.remove('bounce');dc.src=CAT.sit;dc.classList.remove('flip');}if($('audio-state'))$('audio-state').textContent='What changed? What stayed the same? Use the comparison in your plan.';},length*1000);
 }catch{if($('audio-state'))$('audio-state').textContent='Audio could not start. Check that sound is enabled, then try again.';}}

/* Rhythm Lab (student experience) */
const RKEY='music-hero-rhythm-v1';
const rFresh=()=>({done:[false,false,false,false],pattern:[0,0,1,2],best:0});
let rs=rFresh();
try{const saved=JSON.parse(localStorage.getItem(RKEY));if(saved){rs.done=rs.done.map((_,i)=>saved.done?.[i]===true);if(Array.isArray(saved.pattern)&&saved.pattern.length===4&&saved.pattern.every(n=>[0,1,2].includes(n)))rs.pattern=saved.pattern;rs.best=Math.max(0,Math.min(100,Number(saved.best)||0));}}catch{}
let rCur=0,rMaster=null,rTimers=[],rNodes=[],rRun=0,rBusy=false,game=null,tempo=80,listened={beat:false,pattern:false,a:false,b:false},celebrate=false;
const TITLES=['Feel the beat','Notes and rests','Choose the tempo','Rhythm Rescue'],CAPS=['Listen and move','Build a pattern','Compare and listen','Your hero challenge'],SYM=['\u2669','\u266B','\uD834\uDD3D'],NAMES=['Quarter note','Two eighth notes','Quarter rest'];
const unlocked=()=>rs.done.slice(0,3).every(Boolean);
function rPersist(){try{localStorage.setItem(RKEY,JSON.stringify(rs));}catch{}}
function rLater(fn,s){rTimers.push(setTimeout(fn,Math.max(0,s*1000)));}
function rStop(){rRun++;rTimers.forEach(clearTimeout);rTimers=[];rNodes.forEach(n=>{try{n.stop();}catch{}});rNodes=[];rBusy=false;game=null;document.querySelectorAll('.beat').forEach(b=>b.classList.remove('lit'));}
async function rAudio(){try{await ensureAudio();if(!rMaster){rMaster=audioContext.createGain();rMaster.gain.value=.42;rMaster.connect(audioContext.destination);}return true;}catch{const el=$('r-feedback')||$('r-game');if(el){el.textContent='Sound could not start. Check that audio is enabled, then press play again.';el.classList.add('wrong');}return false;}}
function rSound(at,kind='drum'){const ctx=audioContext;if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(rMaster);const t=Math.max(at,ctx.currentTime);o.type=kind==='click'?'triangle':'sine';o.frequency.setValueAtTime(kind==='click'?950:180,t);o.frequency.exponentialRampToValueAtTime(kind==='click'?650:65,t+.1);g.gain.setValueAtTime(kind==='click'?.24:.75,t);g.gain.exponentialRampToValueAtTime(.001,t+.14);o.start(t);o.stop(t+.16);rNodes.push(o);o.onended=()=>{o.disconnect();g.disconnect();rNodes=rNodes.filter(n=>n!==o);};}
function rFlash(i,delay){rLater(()=>document.querySelectorAll('.beat').forEach((b,j)=>b.classList.toggle('lit',j===i%4)),delay);}
function consoleHTML(label='Follow the pulse'){return `<div class="console"><span class="console-label">${label}</span><div class="beat-row" aria-hidden="true">${[1,2,3,4].map(n=>`<span class="beat">${n}</span>`).join('')}</div><div class="console-bottom"><span>Count 1, 2, 3, 4</span><span id="r-bpm">80 BPM</span></div></div>`;}
function rTop(i,intro){return `<div class="work-top"><span class="tag">Mission ${i+1}, +${i===3?40:20} power</span><span>${rs.done[i]?'Completed':i===3?'Listen, then echo':'About 3 minutes'}</span></div><h3 class="title">${TITLES[i]}</h3><p class="intro">${intro}</p>`;}
function rQuestion(title,opts){return `<div class="question"><h4>${title}</h4><div class="answers">${opts.map((x,i)=>`<button class="answer" data-r-answer="${i}">${x}</button>`).join('')}</div><div id="r-feedback" class="feedback" role="status" aria-live="polite"></div><div id="r-next"></div></div>`;}
function rRender(){const xp=rs.done.reduce((s,v,i)=>s+(v?(i===3?40:20):0),0);$('content').innerHTML=`<div class="rl-head"><div><span class="crumb">Rhythm Lab, a student experience for grades 3 to 5</span><h2>Find your rhythm.</h2><p>A steady beat, a little practice, and your first musical superpower.</p></div><div class="power"><span id="r-power-label">Music power: ${xp} of 100</span><progress id="r-power" value="${xp}" max="100"></progress><small>Progress stays in this browser.</small></div></div><div class="rl"><aside><nav class="missions" id="r-missions" aria-label="Rhythm missions"></nav><div class="rl-note"><strong>Small steps, big sound.</strong><br>Listen, give it a try, then try again. That is how musicians grow.<button data-r-teacher>Educator notes and reflection</button><button data-r-reset>Start a fresh adventure</button></div></aside><section id="r-work" class="surface work" tabindex="-1" aria-label="Interactive music lesson"></section><aside class="guide" id="r-guide"></aside></div>`;rChrome();rWork();}
function rChrome(){const hero=rs.done[3];$('r-missions').innerHTML=TITLES.map((t,i)=>{const locked=i===3&&!unlocked();return `<button class="mission ${rCur===i?'active':''} ${rs.done[i]?'done':''}" data-r-mission="${i}" ${locked?'disabled':''} ${rCur===i?'aria-current="step"':''}><span class="num">${rs.done[i]?'\u2713':i+1}</span><span><strong>${t}</strong><small>${locked?'Finish the first three':CAPS[i]}</small></span></button>`;}).join('');
 const xp=rs.done.reduce((s,v,i)=>s+(v?(i===3?40:20):0),0);if($('r-power')){$('r-power').value=xp;$('r-power-label').textContent=`Music power: ${xp} of 100`;}
 const msgs=['Every great rhythm starts with a steady beat. Let\'s find yours!','The beat keeps going, even when your hands are silent.','Tempo is the speed of the beat. Listen for the space between sounds.','The concert needs you! Listen first, then echo the rhythm.'];
 const g=$('r-guide');g.classList.toggle('super',hero);const pose=celebrate?'victory':hero?'hero':['sit','jump','alert','alert'][rCur];const alt=hero?'Maestro Cat in his blue superhero suit and red cape':'Maestro Cat, a friendly orange tabby';
 g.innerHTML=`<div><span class="mode">${hero?'Superhero mode':'Teacher mode'}</span>${catImg(pose,celebrate?'celebrate':'',alt)}</div><div><h3>Maestro Cat</h3><p>"${hero?'You brought the concert back to life. Keep listening, creating, and playing!':msgs[rCur]}"</p><div class="badge ${hero?'earned':''}"><span class="star" aria-hidden="true">${hero?'\u2605':'\u2606'}</span><div><strong>Rhythm Hero badge</strong><small>${hero?'Badge earned. Your rhythm is a superpower!':'Complete the rescue to earn your badge.'}</small></div></div></div>`;celebrate=false;}
function rWork(){rStop();const w=$('r-work');
 if(rCur===0)w.innerHTML=rTop(0,'A beat is music\'s steady pulse. Listen to eight beats and gently pat your knees each time a light turns gold.')+consoleHTML()+`<div class="actions"><button class="primary" data-r-play="beat">Listen and pat along</button><button class="secondary" data-r-stop>Stop sound</button></div><p class="caption">The pulse stays evenly spaced. Count "1, 2, 3, 4" twice.</p>`+rQuestion('What makes a beat steady?',['It gets louder every time.','It repeats at even intervals.','It always gets faster.']);
 if(rCur===1){w.innerHTML=rTop(1,'In this lesson, a quarter note gets one beat. Two eighth notes share that beat. A quarter rest gives you one silent beat.')+`<div class="symbols">${SYM.map((s,i)=>`<div class="symbol"><b aria-hidden="true">${s}</b><span>${NAMES[i]}</span><small>${['1 sound, 1 beat','2 sounds, 1 beat','Silence, 1 beat'][i]}</small></div>`).join('')}</div><div class="question"><h4>Create your four-beat rhythm</h4><p class="caption">Tap each tile to cycle through note, pair, and rest. Try a change, then listen.</p><div id="r-builder" class="builder"></div><div class="actions"><button class="primary" data-r-play="pattern">Play my rhythm</button><button class="secondary" data-r-stop>Stop sound</button></div></div>`+rQuestion('What happens during a quarter rest?',['The beat disappears.','Play two quick sounds.','Stay silent for one beat and keep the pulse.']);rBuilder();}
 if(rCur===2)w.innerHTML=rTop(2,'Tempo means the speed of the beat. Hear the same four-beat rhythm at two speeds, then compare.')+consoleHTML('Listen for the speed')+`<div class="actions"><button class="primary" data-r-play="a">Play A</button><button class="primary" data-r-play="b">Play B</button><button class="secondary" data-r-stop>Stop</button></div><p class="caption" id="r-heard">Listen to both A and B before answering.</p>`+rQuestion('Which version has the faster tempo?',['Version A','Version B','Both have the same tempo']);
 if(rCur===3)w.innerHTML=rTop(3,'The concert\'s rhythm machine has stopped! Listen to the pattern, then echo it with the tap pad or the Space bar. Reach 75% to become a Rhythm Hero.')+`<div class="pattern" aria-label="Quarter, quarter, two eighth notes, rest; quarter, quarter, quarter, quarter">${[0,0,1,2,0,0,0,0].map((n,i)=>`<span aria-hidden="true">${SYM[n]}<small>${i%4+1}</small></span>`).join('')}</div><label class="tempo">Tempo <input id="r-tempo" type="range" min="60" max="100" step="5" value="${tempo}" aria-label="Challenge tempo"><strong id="r-tempo-value">${tempo}</strong> BPM</label>`+consoleHTML('Listen, count in, then your turn')+`<div id="r-game" class="game-state" role="status" aria-live="polite">Ready when you are.</div><button id="r-tap" class="tap">Tap to play<small>Click, touch, or press Space</small></button><div class="actions"><button class="primary" id="r-rescue">Start the rescue</button><button class="secondary" data-r-stop>Stop and retry</button></div><p class="caption">Listen for 8 beats. Count in for 4. Then play for 8. Best score: <span id="r-best">${rs.best}%</span>. Practice score only; device timing may vary.</p><div id="r-result" role="status"></div>`;
 if(rCur<3&&rs.done[rCur])rShowNext();}
function rBuilder(){$('r-builder').innerHTML=rs.pattern.map((n,i)=>`<button class="cell" data-r-cell="${i}" aria-label="Beat ${i+1}: ${NAMES[n]}. Activate to change."><b aria-hidden="true">${SYM[n]}</b><small>Beat ${i+1}</small></button>`).join('');}
function rShowNext(){$('r-next').innerHTML=`<button class="primary" style="margin-top:12px" data-r-next="${rCur+1}">${rCur===2?'Enter Rhythm Rescue':'Next mission'}</button>`;}
function rSelect(i){if(!Number.isInteger(i)||i<0||i>3||(i===3&&!unlocked()))return false;rCur=i;rChrome();rWork();return true;}
function rComplete(i){rs.done[i]=true;rPersist();rChrome();}
async function rPlay(type){rStop();const ticket=rRun;if(!await rAudio()||ticket!==rRun)return;rBusy=true;const ctx=audioContext,t=ctx.currentTime+.12,bpm=type==='a'?70:type==='b'?120:80,step=60/bpm,count=type==='beat'?8:4,pattern=type==='pattern'?rs.pattern.slice():[0,0,0,0],buttons=document.querySelectorAll('[data-r-play]');buttons.forEach(b=>b.disabled=true);if($('r-bpm'))$('r-bpm').textContent=`${bpm} BPM`;
 for(let i=0;i<count;i++){const n=pattern[i%4];if(n!==2){rSound(t+i*step);if(n===1)rSound(t+(i+.5)*step);}rFlash(i,.12+i*step);}
 rLater(()=>{rBusy=false;listened[type]=true;buttons.forEach(b=>b.disabled=false);document.querySelectorAll('.beat').forEach(b=>b.classList.remove('lit'));if($('r-heard'))$('r-heard').textContent=`A: ${listened.a?'heard':'not yet'}. B: ${listened.b?'heard':'not yet'}.`;if($('r-feedback'))$('r-feedback').textContent=type==='pattern'?'Listen again after changing a tile, or answer below.':'Now try the question below.';},.12+count*step);}
function rAnswer(index,el){const correct=[1,2,1][rCur],f=$('r-feedback');f.classList.remove('wrong');const ready=rCur===0?listened.beat:rCur===1?listened.pattern:listened.a&&listened.b;if(!ready&&!rs.done[rCur]){f.textContent=rCur===2?'Listen to both versions all the way through first.':'Listen all the way through first, then try the question.';return;}if(index===correct){el.classList.add('correct');let msg=['Exactly! Evenly spaced beats make a steady pulse.','Yes! Silence belongs in a rhythm, and the pulse keeps going.','That\'s it! B is 120 BPM and A is 70 BPM. More beats per minute means a faster tempo.'][rCur];f.textContent=msg+(rs.done[rCur]?' Mission already completed.':' +20 music power.');rComplete(rCur);rShowNext();}else{f.classList.add('wrong');f.textContent=['Try again. Think about the time between beats.','Try again. A rest is silence with a duration.','Try again. Which version has less time between beats?'][rCur];}}
const OFFSETS=[0,1,2,2.5,4,5,6,7];
function scoreTaps(targets,taps,tol){const used=new Set();let matched=0;for(const tap of taps){let best=-1,d=tol+1;targets.forEach((t,i)=>{const delta=Math.abs(tap-t);if(!used.has(i)&&delta<d){d=delta;best=i;}});if(best>=0&&d<=tol){used.add(best);matched++;}}const extra=taps.length-matched;return{matched,extra,missed:targets.length-matched,score:Math.round(100*matched/(targets.length+extra))};}
async function rRescue(){rStop();const ticket=rRun;if(!await rAudio()||ticket!==rRun)return;rBusy=true;const ctx=audioContext,step=60/tempo,start=ctx.currentTime+.3,playStart=start+12*step;game={start:playStart,end:playStart+8*step,taps:[],targets:OFFSETS.map(n=>playStart+n*step),tol:Math.min(.22,step*.28)};$('r-rescue').disabled=true;$('r-tempo').disabled=true;$('r-result').innerHTML='';$('r-game').textContent='Listen to Maestro: 8 beats.';$('r-bpm').textContent=`${tempo} BPM`;OFFSETS.forEach(n=>rSound(start+n*step));
 for(let i=0;i<20;i++){const t=start+i*step;rFlash(i,t-ctx.currentTime);if(i>=8)rSound(t,'click');if(i===8)rLater(()=>{$('r-game').textContent='Get ready: 1, 2, 3, 4.';},t-ctx.currentTime);if(i===12)rLater(()=>{$('r-game').textContent='Your turn! Echo the pattern.';$('r-tap').focus({preventScroll:true});},t-ctx.currentTime);}
 rLater(rFinish,game.end-ctx.currentTime+.23);}
function rTap(){if(!audioContext||!rMaster)return;rSound(audioContext.currentTime);const pad=$('r-tap');pad.classList.add('pressed');setTimeout(()=>pad.classList.remove('pressed'),100);if(game){const t=audioContext.currentTime;if(t>=game.start-game.tol&&t<=game.end)game.taps.push(t);}}
function rFinish(){if(!game)return;const r=scoreTaps(game.targets,game.taps,game.tol);game=null;rBusy=false;$('r-rescue').disabled=false;$('r-tempo').disabled=false;document.querySelectorAll('.beat').forEach(b=>b.classList.remove('lit'));rs.best=Math.max(rs.best,r.score);rPersist();$('r-best').textContent=`${rs.best}%`;const passed=r.score>=75;if(passed){celebrate=true;rComplete(3);}const advice=r.extra?'Keep the rest silent, and avoid extra taps.':r.missed?'Watch the beat lights and try a slower tempo.':'You kept the rhythm moving!';$('r-game').textContent=passed?'Superhero mode activated!':'Good practice. Ready for another try?';$('r-result').innerHTML=`<div class="result"><h4>${passed?'Rhythm Hero!':`${r.score}%, keep practicing`}</h4><p>${r.score}%. ${r.matched} of 8 sounds matched, ${r.extra} extra taps.</p><p>${passed?'You saved the concert and earned your badge!':advice}</p></div>`;}

/* Events */
$('search').addEventListener('input',e=>{filters.query=e.target.value;renderList();});
$('grade').addEventListener('change',e=>setGrade(e.target.value));
$('domain').addEventListener('change',e=>{filters.domain=e.target.value;renderList();});
$('staff').addEventListener('click',e=>{const b=e.target.closest('[data-grade]');if(b)setGrade(filters.grade===b.dataset.grade?'all':b.dataset.grade);});
$('concept-list').addEventListener('click',e=>{const b=e.target.closest('[data-concept]');if(b){select(b.dataset.concept);if(page==='library'&&window.innerWidth<900)$('content').scrollIntoView({block:'start'});}});
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));
$('home-link').onclick=e=>{e.preventDefault();navigate('library');window.scrollTo({top:0});};
$('hero-browse').onclick=()=>$('content').scrollIntoView({block:'start'});
$('sources-open').onclick=()=>{stopAudio();$('sources').showModal();};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('content').addEventListener('input',e=>{if(page==='rhythm'){if(e.target.id==='r-tempo'){tempo=Number(e.target.value);$('r-tempo-value').textContent=tempo;}return;}const d=draft();if(e.target.id==='coach-response'){d.reply=e.target.value;save();}if(e.target.dataset.field){d.fields[e.target.dataset.field]=e.target.value;save();}if(e.target.dataset.evidence){const id=e.target.dataset.evidence;d.reviews[id]={...d.reviews[id],evidence:e.target.value};save();}});
$('content').addEventListener('change',e=>{if(page==='rhythm')return;const d=draft();if(e.target.id==='scenario-select'){d.scenario=Number(e.target.value);d.decision=null;save();studio();}if(e.target.id==='target-grade'){d.grade=e.target.value;save();studio();}if(e.target.id==='lens'){d.lens=e.target.value;save();}if(e.target.dataset.review){const id=e.target.dataset.review;d.reviews[id]={...d.reviews[id],status:e.target.value};save();}});
$('content').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(page==='rhythm'){if(b.dataset.rPlay)rPlay(b.dataset.rPlay);else if(b.dataset.rAnswer!==undefined)rAnswer(Number(b.dataset.rAnswer),b);else if(b.dataset.rNext){rSelect(Number(b.dataset.rNext));$('r-work').focus();}else if(b.dataset.rCell!==undefined){if(rBusy)rStop();const i=Number(b.dataset.rCell);rs.pattern[i]=(rs.pattern[i]+1)%3;rPersist();rBuilder();}else if(b.hasAttribute('data-r-stop')){rStop();rWork();}else if(b.id==='r-rescue')rRescue();else if(b.id==='r-tap')rTap();else if(b.dataset.rMission!==undefined&&!b.disabled)rSelect(Number(b.dataset.rMission));else if(b.hasAttribute('data-r-teacher')){rStop();$('teacher').showModal();}else if(b.hasAttribute('data-r-reset'))$('reset-dialog').showModal();return;}
 const d=draft();if(b.dataset.nav)navigate(b.dataset.nav);if(b.hasAttribute('data-sources'))$('sources').showModal();if(b.dataset.idea!==undefined){const idea=experiences(concept())[Number(b.dataset.idea)];d.fields[idea.field]+=(d.fields[idea.field]?'\n\n':'')+'Planning seed to adapt: '+idea.body;save();navigate('studio');say('I added that planning seed to your draft. Adapt it to your learners and objective.','side');}
 if(b.dataset.decision!==undefined){d.decision=Number(b.dataset.decision);save();studio();say(d.decision===1?'Good instinct. Now decide what response would count as evidence.':'Read the feedback in the scenario, then try another choice.',d.decision===1?'victory':'alert');}
 if(b.id==='coach-prompt')addPrompt();if(b.id==='coach-send'){const input=$('coach-response');const text=input.value.trim();if(!text){toast('Write a response before continuing.');return;}d.dialogue.push({role:'learner',text,at:Date.now()});input.value='';d.reply='';addPrompt();}
 if(b.id==='review-draft')reviewDraft();if(b.id==='snapshot'&&snapshot())say('Revision saved. Compare it in My revisions whenever you are ready.','victory');if(b.id==='export')exportLesson();
 if(b.dataset.compare){compareId=b.dataset.compare;renderComparison();$('comparison').scrollIntoView({block:'start'});}if(b.dataset.restore){restoreId=b.dataset.restore;$('restore').showModal();}if(b.dataset.audio)playDemo(b.dataset.audio);if(b.hasAttribute('data-stop-audio'))stopAudio();});
$('restore-confirm').onclick=()=>{const d=draft(),v=d.versions.find(x=>x.id===restoreId);if(!v)return;snapshot('Before restoring a previous revision');d.fields={...v.fields};d.grade=v.grade;d.scenario=v.scenario;d.reviews=JSON.parse(JSON.stringify(v.reviews||{}));save();$('restore').close();navigate('studio');say('Revision restored. Your previous draft is still in the history.','stretch');};
$('confirm-reset').onclick=()=>{rStop();rs=rFresh();rCur=0;listened={beat:false,pattern:false,a:false,b:false};rPersist();$('reset-dialog').close();rRender();};
try{$('reflection').value=localStorage.getItem(RKEY+'-reflection')||'';}catch{}
$('reflection').oninput=()=>{try{localStorage.setItem(RKEY+'-reflection',$('reflection').value);}catch{$('reflection-status').textContent='Notes could not be saved in this browser.';}};
document.addEventListener('keydown',e=>{if(page==='rhythm'&&rCur===3&&e.code==='Space'&&!e.repeat&&!document.querySelector('dialog[open]')&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&(!e.target.closest('button')||e.target.id==='r-tap')){e.preventDefault();rTap();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAudio();if(rBusy){rStop();if(page==='rhythm'){rWork();if($('r-game'))$('r-game').textContent='Paused while you were away. Start again when ready.';}}}});
$('dock-img').src=CAT.side;$('dock-img').classList.add('flip');
renderStaff();renderList();render();{const h=location.hash.slice(1);if(['studio','revisions','rhythm'].includes(h))navigate(h);}
window.addEventListener('hashchange',()=>{const h=location.hash.slice(1)||'library';if(h!==page&&['library','studio','revisions','rhythm'].includes(h))navigate(h);});
